title: Deadlines for PAU # (Maintained by @abhshkdz)
email: vincent.major@nyumc.org
description: Deadline countdowns for the NYULH PAU. This is a fork of the original AI Deadlines by @abhshkdz
author: Vincent Major

twitter_username: vincentjmajor
github_username: vincentmajor
github_repo: pau-deadlines

markdown: kramdown
ga_id: UA-36274081-2
