title: Deadlines for PAU # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Deadline countdowns for the NYULH PAU. This is a fork of the original AI Deadlines by abhshkdz
author: Abhishek Das

twitter_username: abhshkdz
twitter_hashtag: machinelearning
github_username: abhshkdz
github_repo: pau-deadlines

markdown: kramdown
ga_id: UA-36274081-2
